### ISSUE TITLE
Add a description to the repository

### ISSUE THREAD

**Issue by sertansenturk** [miracatici/note_model#4]
There is no description for the repository:
![note_model](https://cloud.githubusercontent.com/assets/4540641/12479015/bf512d00-c038-11e5-8d8c-f63f6d078591.png)

Add this: 

 "Tools to compute note models from audio pitch distribution analysis"

**Comment by miracatici** [comment]
I guess due to GitHub, there is a problem about adding description for the repository. I'll try again later.

**Comment by miracatici** [comment]
Closed
